### PR TITLE
OptimizedLegends

### PR DESCRIPTION
**Pull request by andreiPro**
OptimizedLegends

### CODE REVIEW

**Comment by andreiPro** [comment]
Optimized code of Legends. Now working better.

**Comment by andreiPro** [comment]
Changes:
1. Optimized the code for previous Legends, sections: 'Socioeconomic Layers' & 'Geodata Layers';
2. Now working Legend for section 'Vulnerability'.

**Comment by Skerre** [comment]
Thank you I am checking this now

**Comment by Skerre** [comment]
@andreiPro I love the change you did for the vulnerability legends, however I get unexpected behavior when I open socio economic layers: when I restart the application, I cannot see the legend the first time I open it and if I change opacity or hover with mouse on top of empty legend, it may reappear when I check / uncheck the layer I selected. Sometimes it also never comes, its inconsistent somehow. Does it always 100% work on your computer?
Could you do a Shift Refresh or total restart of the app and then try again?

inconsistent_behaviour

**Comment by Skerre** [comment]
Closing since newer version has been released

**Pull request closed without merging**
