### PR TITLE
New-reset-button

### PR DESCRIPTION
**Pull request by andreiPro**

### CODE REVIEW

**Comment by andreiPro** [comment]
Good morning,
New Reset-button.

image

**Comment by andreiPro** [comment]
Dear Team,
Let's use Immer library for avoiding of mutation of state. Really helpful library.

https://yarnpkg.com/package/immer
https://dev.to/franciscomendes10866/use-context-api-and-immer-to-manage-the-state-of-your-react-app-1hem

**Comment by Skerre** [comment]
@andreiPro Dear Andrei, I checked the PR and I noticed something:


https://user-images.githubusercontent.com/38685413/201301434-f3ad9831-5004-407e-90ef-8338e1b6204a.mp4

I think it still does not reappear the vulnerability points after using the reset button

**Comment by andreiPro** [comment]
Hi Martin,
As I remember this vulnerability points should be active be default.
I can easily make the not active be default.

**Comment by andreiPro** [comment]
> @andreiPro Dear Andrei, I checked the PR and I noticed something:
> 
>  unexpected_behaviour.mp4 
> I think it still does not reappear the vulnerability points after using the reset button

Good morning Martin,
This bug is fixed.

**Comment by andreiPro** [comment]
Hi Martin,
I've fixed all bugs.

**Comment by andreiPro** [comment]
reset-button

**Pull request merged**
